version: "3"

services:
  app:
    build: .
    depends_on:
      - db
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=db
    ports:
      - 8000:8000


  db:
    image: postgres:14.1
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
