# Generated by Django 4.0.3 on 2022-04-16 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(choices=[('ERKAK', 'Erkak'), ('AYOL', 'Ayol')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('year', models.DateField()),
                ('imdb', models.IntegerField()),
                ('genre', models.CharField(choices=[('DRAMA', 'Drama'), ('KOMSEDIYA', 'Komediya'), ('DETIKTIV', 'Detiktiv'), ('ROMANTIKA', 'Romantika'), ('FANTASTIK', 'Fantastik'), ('JANGARI', 'Jangari')], max_length=9)),
                ('actors', models.ManyToManyField(blank=True, related_name='actors', to='studio.actor')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.movie')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='actor',
            name='movies',
            field=models.ManyToManyField(blank=True, related_name='movies', to='studio.movie'),
        ),
    ]
